server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  sql:
    init:
      mode: always
      encoding: utf-8
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

