spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306
    url: jdbc:mysql://localhost:3306/my_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  sql:
    init:
      mode: never
#      mode: always
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
